networks:
  default:

services:
  service-a:
    build: ./service-a
    container_name: service-a
    environment:
      - SERVICE_B_BASE_URL=http://service-b:8080
    networks:
      - default
    depends_on:
      - service-b

  service-b:
    build: ./service-b
    container_name: service-b
    networks:
      - default
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 2s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - default
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - default
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards