{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Circuit Breaker State",
   "type": "timeseries",
   "description": "0 - Closed\n1 - Half Open\n2 - Open",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "circuit_breaker_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Circuit Breaker Calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(circuit_breaker_calls_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests to ServiceB",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{status}}" }
   ]
  }
 ]
}